### ISSUE TITLE
Forward consultation request to Basecamp

### ISSUE THREAD

**Issue by ppalms** [ppalms/ok-wildscapes-api#5]
# Consultation workflow

When consultation request is received, forward to save-96Kpu69SrAcm@3.basecamp.com so it will show up in the OK Wildscapes Basecamp project.

Remove hard-coded email addresses in thee requestConsultation function and replace with SSM params.

**Source**: no-reply@okwildscapes.com

**Destination**: 
- ToAddresses:
  - dev: patrick@okwildscapes.com OR mailgun with automated test
  - prod: contact@okwildscapes.com
- BccAddresses:
  - save-96Kpu69SrAcm@3.basecamp.com

## Tasks

- [ ] Push hard-coded version to get Basecamp working
- [ ] Add Middy and SSM params
- [ ] Refactor endpoint to use pipeline resolver - first stage saves to DDB, second stage publishes to OK Wildscapes SNS topic using AMAZON_SNS data source
